name: 'Convert to zip'

on: 
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  Convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Archive
        working-directory: lib
        run: zip -r Monocon.zip Monocon

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: lib/Monocon.zip
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
